name: GitHub FORCE test
run-name: ${{ github.actor }} is testing out FORCE
on:
  [push]
  schedule:
    - cron: '0 18 * * *'
jobs:
  Test-FORCE-Linux:
    runs-on: [self-hosted, linux]
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: rm -Rf raven && git clone https://github.com/idaholab/raven.git
      - run: python3 raven/scripts/install_plugins.py -s TEAL
      - run: python3 raven/scripts/install_plugins.py -s HERON
      - run: WD=`(cd ../../.. && pwd)` && export RAVEN_LIBS_NAME="raven_libs_"`basename $WD` && raven/scripts/establish_conda_env.sh --install
      - run: cd raven && ./build_raven
      - run: raven/run_tests --library-report
      - run: PATH="$PATH:`pwd`/raven" && cd use_cases && python3 model_run.py
